@startuml Rol

!include rol_parcial.puml

show Rol

note right of Rol::alcance
    emun:
        SISTEMA,
        PROXECTO,
        ETAPA,
        HISTORIA,
        ACTUACION
end note

note right of Rol::permisos
    [
        read,
        create,
        update,
        delete
    ]
end note

@enduml