@startuml Rol

class Rol {
    {field} nome: string
    {field} descricion: string
    {field} alcance: enum
    {field} permisos: boolean[]

    {method} create()
    {method} update()
    {method} delete()
}

hide Rol

@enduml