@startuml Usuario

!include rol_parcial.puml

!startsub PARCIAL
    class Usuario {
        {field} nome: string
        {field} apelido1: string
        {field} apelido2: string
        {field} salario: number
        {method} create()
        {method} update()
        {method} delete()
    }

    class Horario {
        {field} horasSemanais: number
        {field} traballaFindes: boolean
        {field} horarioFlexible: boolean
        {field} festivos: Date[]
    }

    class Horario {
        {field} tipo: string
        {field} contacto: string
    }

    hide Usuario
    hide Horario
    hide Contacto

    Usuario "1..*" -- Contacto
    Usuario "1..*" -- Rol
    Usuario "0..*" -- Horario
!endsub

@enduml
