@startuml Usuario

' ################################################################################
' ## Actuacion
' ################################################################################

class Actuacion  #LightGreen ##Green {
    ' Propiedades
    {field} data_creacion: Date
    {field} data_ini: Date
    {field} data_fin: Date
    {field} data_ini_prevista: Date
    {field} data_fin_prevista: Date

    {field} nome: string
    {field} descricion: string

    {field} horas_estimadas: number
    {field} horas_consumidas: number
    {field} euros_estimados: number
    {field} euros_consumidos: number

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()

    {method} calcularCustesEstimados()
    {method} calcularCustesConsumidos()
}

' ################################################################################
' ## Comentario
' ################################################################################

class Comentario #LightGrey ##Black {
    ' Propiedades
    {field} data_creacion: Date
    {field} data_expiracion?: Date

    {field} titulo: string
    {field} mensaxe: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## EstimacionTempo
' ################################################################################

class EstimacionTempo #Gold ##GoldenRod{
    ' Propiedades
    {field} nome: string
    {field} descricion: string
    {field} escala: enum
    {field} duracion: number

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## Etapa
' ################################################################################

class Etapa #LightCyan ##Cyan {
    ' Propiedades
    {field} data_ini: Date
    {field} data_fin: Date
    {field} data_ini_prevista: Date
    {field} data_fin_prevista: Date

    {field} nome: string
    {field} descricion: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## Estado
' ################################################################################

class Estado #LimeGreen ##DarkGreen {
    ' Propiedades
    {field} nome: string
    {field} descricion: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

class HistoricoEstado #GreenYellow ##DarkGreen {
    ' Propiedades
    {field} data_creacion: Date
    {field} log: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## HistoriaProduto
' ################################################################################

class HistoriaProduto #Khaki ##DarkKhaki {
    ' Propiedades
    {field} data_creacion: Date
    {field} data_ini: Date
    {field} data_fin: Date
    {field} data_ini_prevista: Date
    {field} data_fin_prevista: Date

    {field} nome: string
    {field} descricion: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## Prioridade
' ################################################################################

class Prioridade #LightPink ##DeepPink {
    ' Propiedades
    {field} nome: string
    {field} descricion: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## Proxecto
' ################################################################################

class Proxecto #LightSteelBlue ##SteelBlue {
    ' Propiedades
    {field} data_ini: Date
    {field} data_fin: Date
    {field} data_ini_prevista: Date
    {field} data_fin_prevista: Date

    {field} nome: string
    {field} descricion: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## Repo
' ################################################################################

class Repo #GhostWhite ##OrangeRed {
    ' Propiedades
    {field} data_creacion: Date
    {field} data_expiracion?: Date

    {field} nome: string
    {field} descricion: string
    {field} uri: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## Rol
' ################################################################################

class Rol #LightBlue ##DarkBlue {
    ' Propiedades
    {field} nome: string
    {field} descricion: string
    {field} alcance: enum
    {field} permisos: boolean[]

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## Tipo
' ################################################################################

class Tipo #Wheat ##RosyBrown {
    ' Propiedades
    {field} nome: string
    {field} descricion: string

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

' ################################################################################
' ## Usuario
' ################################################################################

class Usuario #APPLICATION ##Blue {
    ' Propiedades
    {field} nome: string
    {field} apelido1: string
    {field} apelido2: string
    {field} salario: number

    ' Métodos
    {method} create()
    {method} update()
    {method} delete()
}

class Horario #AliceBlue ##Blue {
    ' Propiedades
    {field} horasSemanais: number
    {field} traballaFindes: boolean
    {field} horarioFlexible: boolean
    {field} festivos: Date[]
}

class Contacto #AliceBlue ##Blue {
    ' Propiedades
    {field} tipo: string
    {field} contacto: string
}

' ################################################################################
' ## RELACIÓNS
' ################################################################################

'Actuacion

Actuacion -- "creador" Usuario #Blue
Actuacion "1..*" o-- "participan" Usuario #Blue
Actuacion "0..*" o-- Usuario  #Blue: Validadores <
Actuacion "1..*" o-- Rol #DarkBlue : Asignados <
Actuacion "0..*" o-- Comentario #Black
Actuacion "0..*" --o HistoriaProduto #Green

'Comentario
Comentario -- Usuario #Blue : Creador
Comentario "1..*" o-- Rol #DarkBlue : Visivilidade <

'Etapa
Etapa - Estado #DarkGreen

Etapa "1..*" o-- "participan" Usuario #Blue
Etapa "0..*" o-- Usuario #Blue : Validadores <
Etapa "1..*" o-- Rol #DarkBlue : Asignados <
Etapa "0..*" o-- Comentario #Black

Etapa "0..*" --o Proxecto #SteelBlue
Etapa "0..*" --o Actuacion #Green
Etapa "0..*" --o HistoriaProduto

'EstimacionTempo
EstimacionTempo -- HistoriaProduto #GoldenRod
EstimacionTempo -- Actuacion #GoldenRod

'Estado
Estado -- Actuacion #DarkGreen
Estado -- Proxecto #DarkGreen
Estado -- HistoriaProduto #DarkGreen

'HistoricoEstado
HistoricoEstado -- Usuario #Blue : Creador
HistoricoEstado "1..*" o-- Rol #DarkBlue : Visivilidade <
HistoricoEstado - Estado #DarkGreen : Previo
HistoricoEstado - Estado #DarkGreen : Novo

'HistoriaProduto
HistoriaProduto "0..*" o-- HistoriaProduto #DarkKhaki : Dependencias
HistoriaProduto -- Usuario #Blue : creador
HistoriaProduto "1..*" o-- "participan" Usuario #Blue
HistoriaProduto "0..*" o-- Usuario #Blue : Validadores <
HistoriaProduto "0..*" o-- Repo #OrangeRed
HistoriaProduto "1..*" o-- Rol #DarkBlue : Asignados <
HistoriaProduto "0..*" o-- Comentario #Black
HistoriaProduto "0..*" --o Proxecto #DarkKhaki

'Prioridade
Prioridade -- Actuacion #DeepPink
Prioridade -- HistoriaProduto #DeepPink

'Proxecto

Proxecto "1..*" o-- "participan" Usuario #Blue
Proxecto "0..*" o-- Usuario #Blue : Validadores <
Proxecto "1..*" o-- Rol #DarkBlue : Asignados <
Proxecto "0..*" o-- Repo #OrangeRed
Proxecto "0..*" o-- Comentario #Black

'Repo
Repo -- Usuario #Blue : Creador
Repo "1..*" -- Rol #DarkBlue : Visivilidade <

'Rol

'Tipo
Tipo -- HistoriaProduto #RosyBrown
Tipo -- Actuacion #RosyBrown

'Usuario
Usuario "1..*" o- Rol #DarkBlue
Usuario "1..*" *-- Contacto #Blue
Usuario "0..*" *-- Horario #Blue

@enduml