@startuml Etapa

!startsub PARCIAL
    class Etapa #LightCyan ##Cyan {
        ' Propiedades
        {field} data_ini: Date
        {field} data_fin: Date
        {field} data_ini_prevista: Date
        {field} data_fin_prevista: Date

        {field} nome: string
        {field} descricion: string

        ' Métodos
        {method} create()
        {method} update()
        {method} delete()
    }

    Etapa - Estado #DarkGreen

    Etapa "1..*" o-- "participan" Usuario #Blue
    Etapa "0..*" o-- Usuario #Blue : Validadores <
    Etapa "1..*" o-- Rol #DarkBlue : Asignados <
    Etapa "0..*" o-- Comentario #Black
!endsub

@enduml