@startuml HistoriaProduto

!startsub PARCIAL
    class HistoriaProduto #Khaki ##DarkKhaki {
        ' Propiedades
        {field} data_creacion: Date
        {field} data_ini: Date
        {field} data_fin: Date
        {field} data_ini_prevista: Date
        {field} data_fin_prevista: Date

        {field} nome: string
        {field} descricion: string

        ' Métodos
        {method} create()
        {method} update()
        {method} delete()
    }

    Etapa "0..*" --o HistoriaProduto
    HistoriaProduto "0..*" o-- HistoriaProduto #DarkKhaki : Dependencias

    Estado -- HistoriaProduto #DarkGreen
    EstimacionTempo -- HistoriaProduto #GoldenRod
    Prioridade -- HistoriaProduto #DeepPink
    Tipo -- HistoriaProduto #RosyBrown

    Actuacion "0..*" --o HistoriaProduto #Green


    HistoriaProduto -- Usuario #Blue : creador
    HistoriaProduto "1..*" o-- "participan" Usuario #Blue
    HistoriaProduto "0..*" o-- Usuario #Blue : Validadores <
    HistoriaProduto "0..*" o-- Repo #OrangeRed
    HistoriaProduto "1..*" o-- Rol #DarkBlue : Asignados <
    HistoriaProduto "0..*" o-- Comentario #Black
!endsub

@enduml