@startuml Proxecto

!startsub PARCIAL
    class Proxecto #LightSteelBlue ##SteelBlue {
        ' Propiedades
        {field} data_ini: Date
        {field} data_fin: Date
        {field} data_ini_prevista: Date
        {field} data_fin_prevista: Date

        {field} nome: string
        {field} descricion: string

        ' Métodos
        {method} create()
        {method} update()
        {method} delete()
    }

    Estado -- Proxecto #DarkGreen
    Etapa "0..*" --o Proxecto #SteelBlue
    HistoriaProduto "0..*" --o Proxecto #DarkKhaki

    Proxecto "1..*" o-- "participan" Usuario #Blue
    Proxecto "0..*" o-- Usuario #Blue : Validadores <
    Proxecto "1..*" o-- Rol #DarkBlue : Asignados <
    Proxecto "0..*" o-- Repo #OrangeRed
    Proxecto "0..*" o-- Comentario #Black
!endsub

@enduml