@startuml Usuario

!startsub PARCIAL
    class Usuario #APPLICATION ##Blue {
        ' Propiedades
        {field} nome: string
        {field} apelido1: string
        {field} apelido2: string
        {field} salario: number

        ' Métodos
        {method} create()
        {method} update()
        {method} delete()
    }

    class Horario #AliceBlue ##Blue {
        ' Propiedades
        {field} horasSemanais: number
        {field} traballaFindes: boolean
        {field} horarioFlexible: boolean
        {field} festivos: Date[]
    }

    class Contacto #AliceBlue ##Blue {
        ' Propiedades
        {field} tipo: string
        {field} contacto: string
    }

    Usuario "1..*" - Rol #DarkBlue
    Usuario "1..*" -- Contacto #Blue
    Usuario "0..*" -- Horario #Blue
!endsub

@enduml
