@startuml CUOwnerActores

!include casos_uso_propietario.puml

' Actores
actor "Propietario Produto" as owner

' ######################################################################################
' ## Relacións Actores
' ######################################################################################
owner -- VerProxectoOwner

@enduml

