@startuml CUAdminActores

!include casos_uso_admin.puml

' Actores
actor "Desenvolvedor" as dev
actor "Administrador" as admin

' ######################################################################################
' ## Relacións Actores
' ######################################################################################
dev <|- admin
admin -- VerProxectoAdmin
admin -- CrearProxectoAdmin

@enduml

