@startuml CUComercial

' ######################################################################################
' ## Estilos
' ######################################################################################
left to right direction

skinparam actor {
    Style awesome

    BackgroundColor #ccddff
    BorderColor #001a4d
}

skinparam usecase {
    BorderColor #001a4d
    ArrowColor Blue
}

' ######################################################################################
' ## Diagrama
' ######################################################################################

' Actores
actor "Propietario Produto" as owner
actor Comercial

' Casos de uso

' ######################################################################################
' ## Relacións Actores
' ######################################################################################
owner <|- Comercial

' ######################################################################################
' ## Relacións Casos de uso
' ######################################################################################

@enduml

